# Generated by Django 3.1 on 2020-11-20 21:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=50, unique=True)),
                ('private_key', models.CharField(max_length=255, unique=True)),
                ('public_key', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(default='10.0.0.1/24', max_length=255, unique=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('listen_port', models.BigIntegerField(default=51820, null=True, unique=True)),
                ('post_up', models.TextField(max_length=255)),
                ('post_down', models.TextField(max_length=255)),
                ('save_config', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('private_key', models.CharField(max_length=255, unique=True)),
                ('public_key', models.CharField(max_length=255, unique=True)),
                ('preshared_key', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('listen_port', models.BigIntegerField(default=51820, null=True)),
                ('allowed_ips', models.CharField(default='0.0.0.0/0, ::/0', max_length=255)),
                ('dns', models.CharField(default='1.1.1.1, 1.0.0.1', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peers', to='wireguard.server')),
            ],
        ),
    ]
